//登录
function login(){
	$.ajax({
		type:"get",
		url:"http://127.0.0.1:3000/login",
		data:{
			name:$('#username').val(),
			pass:$('#userpass').val()
		},
		async:true,
		dataType:'JSON',
		success:function(res){
			$('.alert').hide();
			console.log(res);
			if(res.result=='1'){
				$('.alert-success').show();
				setTimeout(function(){
					window.location.href="../index.html";
				},2000)
			}else{
				$('.alert-danger').show();
			}
		},error:function(res){
			console.log(res)
		}
	});
	return false;
}
//注册
function register(){
	$.ajax({
		type:"get",
		url:"http://127.0.0.1:3000/register",
		data:{
			name:$('#username').val(),
			pass:$('#userpass').val()
		},
		async:true,
		dataType:'JSON',
		success:function(res){
			$('.alert').hide();
			console.log(res);
			if(res.result=='success'){
				$('.alert-success').show();
				setTimeout(function(){
					window.location.href="login.html";
				},2000)
				
			}else{
				$('.alert-danger').show();
			}
		},error:function(res){
			console.log(res)
		}
	});
	return false;
}

//删除
$('.index').on('click','.del',function(){
	console.log($(this).prev().html());
	var delname=$(this).prev().html();
	$.ajax({
		type:"get",
		url:"http://127.0.0.1:3000/del_user",
		data:{
			name:delname
		},
		async:true,
		dataType:'JSON',
		success:function(res){
			console.log(res);
			if(res.result=='success'){
				window.location.reload()
			}else{
				alert('删除失败');
			}
		},error:function(res){
			console.log(res);
		}
	});
})

//修改密码
var changePassName='';
$('.index').on('click','.change-pass',function(){
	console.log($(this).prev().html());
	changePassName=$(this).prev().html();
})
$('.change-val').click(function(){
	$.ajax({
		type:"get",
		url:"http://127.0.0.1:3000/change_pass",
		data:{
			name:changePassName,
			newpass: $('#newpass').val()
		},
		async:true,
		dataType:'JSON',
		success:function(res){
			console.log(res);
			if(res.result=='success'){
				alert('修改成功')
			}else{
				alert('修改失败');
			}
		},error:function(res){
			console.log(res);
		}
	});
})
